# Generated by Django 6.0.2 on 2026-02-12 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITLIST', 'Waitlist')], default='PENDING', max_length=20)),
                ('application_type', models.CharField(choices=[('ONLINE', 'Online Application'), ('OFFLINE', 'Paper Application')], default='ONLINE', max_length=20)),
                ('name_with_initials', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(default='Sinhalese', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('student_nic', models.CharField(blank=True, max_length=20, verbose_name='NIC')),
                ('current_school', models.CharField(blank=True, max_length=200)),
                ('siblings_info', models.TextField(blank=True, help_text='Names and levels of siblings currently attending')),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_contact_number', models.CharField(max_length=20)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('father_name', models.CharField(max_length=200)),
                ('father_contact_number', models.CharField(max_length=20)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('home_address', models.TextField()),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('schedule_preferences', models.JSONField(blank=True, default=dict, help_text='Preferred class days and times')),
                ('selected_class_day', models.CharField(blank=True, max_length=100)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, upload_to='signatures/')),
                ('special_comments', models.TextField(blank=True)),
                ('authorized_by', models.CharField(blank=True, max_length=100)),
                ('authorization_date', models.DateField(blank=True, null=True)),
                ('application_form_scan', models.FileField(blank=True, upload_to='applications/scans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('GUARDIAN', 'Legal Guardian')], max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('name_with_initials', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('home_address', models.TextField()),
                ('primary_contact_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('profile_picture', models.ImageField(blank=True, upload_to='student_profiles/')),
                ('current_school', models.CharField(blank=True, max_length=200)),
                ('current_level', models.CharField(choices=[('STARTERS', 'Pre A1 Starters'), ('MOVERS', 'A1 Movers'), ('FLYERS', 'A2 Flyers')], default='STARTERS', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.CharField(blank=True, max_length=50)),
                ('total_points', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_student', to='students.application')),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='courses.class')),
                ('guardians', models.ManyToManyField(related_name='students', to='students.guardian')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=100)),
                ('badge_type', models.CharField(choices=[('SKILL_MASTERY', 'Skill Mastery'), ('LEVEL_COMPLETE', 'Level Completion'), ('EXAM_PASSED', 'Exam Passed'), ('PERFECT_SCORE', 'Perfect Score'), ('STREAK', 'Daily Streak'), ('PARTICIPATION', 'Participation')], max_length=50)),
                ('badge_icon', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skill_type', models.CharField(blank=True, choices=[('LISTENING', 'Listening'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20, null=True)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='courses.ylelevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='students.student')),
            ],
            options={
                'ordering': ['-earned_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused Absence')], max_length=20)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Reason for absence/lateness')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.class')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'class_session', 'date')},
            },
        ),
    ]
