# Generated by Django 6.0.2 on 2026-02-26 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='guardian_signature_date',
            field=models.DateField(blank=True, help_text='Date guardian signed the form', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='processing_date',
            field=models.DateField(blank=True, help_text='Date application was processed', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('AWAITING_TEST', 'Awaiting Baseline Test'), ('TEST_COMPLETED', 'Baseline Test Completed'), ('LEVEL_ASSIGNED', 'Level Assigned'), ('APPROVED', 'Approved for Enrollment'), ('ENROLLED', 'Enrolled'), ('REJECTED', 'Rejected'), ('WAITLIST', 'Waitlist')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='BaselineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('listening_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reading_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('writing_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('speaking_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recommended_level', models.CharField(blank=True, choices=[('STARTERS', 'Pre A1 Starters'), ('MOVERS', 'A1 Movers'), ('FLYERS', 'A2 Flyers')], max_length=20)),
                ('assigned_level', models.CharField(blank=True, choices=[('STARTERS', 'Pre A1 Starters'), ('MOVERS', 'A1 Movers'), ('FLYERS', 'A2 Flyers')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Test observations or special remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_test', to='students.application')),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_tests_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baseline Test',
                'verbose_name_plural': 'Baseline Tests',
                'ordering': ['-test_date'],
            },
        ),
    ]
