# Generated by Django 6.0.2 on 2026-02-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_baseline_test_and_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
