# Generated by Django 6.0.1 on 2026-02-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_nationality_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Unique reference number in format A{YYMMDD}-{ID}', max_length=20, null=True, unique=True),
        ),
    ]
