# Generated by Django 6.0.1 on 2026-03-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_application_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, help_text='Date from scanned form or auto-set on creation', null=True),
        ),
    ]
