# Generated by Django 6.0.2 on 2026-03-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_update_application_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
