# Generated by Django 6.0.2 on 2026-03-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_make_primary_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_page1',
            field=models.ImageField(blank=True, upload_to='applications/pages/'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_page2',
            field=models.ImageField(blank=True, upload_to='applications/pages/'),
        ),
        migrations.AddField(
            model_name='application',
            name='handwriting_detection_method',
            field=models.CharField(blank=True, default='', help_text='Method used for handwriting detection (e.g., Google Cloud Vision)', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='handwriting_percentage',
            field=models.IntegerField(default=0, help_text='Percentage of handwritten content detected (0-100)'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_handwritten',
            field=models.BooleanField(default=False, help_text='Whether the form is handwritten'),
        ),
    ]
