# Generated by Django 6.0.5 on 2026-05-25 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_add_handwriting_detection_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document1',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='document1_type',
            field=models.CharField(blank=True, choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PHOTO', 'Photo'), ('PASSPORT', 'Passport'), ('VACCINATION', 'Vaccination Record'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='document2',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='document2_type',
            field=models.CharField(blank=True, choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PHOTO', 'Photo'), ('PASSPORT', 'Passport'), ('VACCINATION', 'Vaccination Record'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='applications/qr_codes/'),
        ),
        migrations.CreateModel(
            name='QRAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(db_index=True, max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_attendance_records', to='students.student')),
            ],
            options={
                'verbose_name': 'QR Attendance Scan',
                'verbose_name_plural': 'QR Attendance Scans',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['admission_number', '-scanned_at'], name='students_qr_admissi_43b6b1_idx')],
            },
        ),
    ]
