# Generated by Django 6.1.1 on 2026-09-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_refresh_class_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_level',
            field=models.CharField(default='STARTERS', max_length=20),
        ),
    ]
