# Generated by Django 6.1.1 on 2026-09-16 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def retire_vaccination_type(apps, schema_editor):
    """Vaccination Record was removed as a document type; keep existing files as Other."""
    Application = apps.get_model("students", "Application")
    Application.objects.filter(document1_type="VACCINATION").update(document1_type="OTHER")
    Application.objects.filter(document2_type="VACCINATION").update(document2_type="OTHER")


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_backfill_class_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-application_date'], 'permissions': [('view_upload_log', 'Can view application upload log')]},
        ),
        migrations.AddField(
            model_name='application',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='document1_type',
            field=models.CharField(blank=True, choices=[('APPLICATION_BACKSIDE', 'Backside of the Application'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PHOTO', 'Photo'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='application',
            name='document2_type',
            field=models.CharField(blank=True, choices=[('APPLICATION_BACKSIDE', 'Backside of the Application'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PHOTO', 'Photo'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.RunPython(retire_vaccination_type, migrations.RunPython.noop),
    ]
