# Generated by Django 6.1.1 on 2026-09-16 08:22

from django.db import migrations


def delete_upload_log_permission(apps, schema_editor):
    """The upload log is superuser-only, so the permission must not stay assignable to groups."""
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(content_type__app_label="students", codename="view_upload_log").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('students', '0013_application_uploaded_by_and_document_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-application_date']},
        ),
        migrations.RunPython(delete_upload_log_permission, migrations.RunPython.noop),
    ]
