# Generated by Django 6.1.1 on 2026-09-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_upload_log_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselinetest',
            name='assigned_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='baselinetest',
            name='recommended_level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
