# Generated by Django 6.1.1 on 2026-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_baseline_levels_from_yle_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_level',
            field=models.CharField(default='PRE_A1', max_length=20),
        ),
    ]
