# Generated by Django 6.1.1 on 2026-09-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='document1_type',
            field=models.CharField(blank=True, choices=[('APPLICATION_BACKSIDE', 'Backside of the Application'), ('PLACEMENT_TEST_PAPER', 'Placement Test Paper'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PHOTO', 'Photo'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='application',
            name='document2_type',
            field=models.CharField(blank=True, choices=[('APPLICATION_BACKSIDE', 'Backside of the Application'), ('PLACEMENT_TEST_PAPER', 'Placement Test Paper'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PHOTO', 'Photo'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=32),
        ),
    ]
