# Generated by Django 6.1.1 on 2026-09-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_placement_test_paper_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document3',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='document3_type',
            field=models.CharField(blank=True, choices=[('APPLICATION_BACKSIDE', 'Backside of the Application'), ('PLACEMENT_TEST_PAPER', 'Placement Test Paper'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PHOTO', 'Photo'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='document4',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='document4_type',
            field=models.CharField(blank=True, choices=[('APPLICATION_BACKSIDE', 'Backside of the Application'), ('PLACEMENT_TEST_PAPER', 'Placement Test Paper'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PHOTO', 'Photo'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=32),
        ),
    ]
