# Generated by Django 6.1.1 on 2026-09-20 02:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_application_document_slots_3_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
    ]
