# Generated by Django 6.1.1 on 2026-09-21 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_application_payments'),
        ('students', '0020_local_date_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='payments.applicationpaymentrun'),
        ),
    ]
