# Generated by Django 6.0.2 on 2026-02-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('template_type', models.CharField(choices=[('STARTERS', 'Pre A1 Starters'), ('MOVERS', 'A1 Movers'), ('FLYERS', 'A2 Flyers'), ('SKILL', 'Skill Mastery'), ('ACHIEVEMENT', 'Special Achievement')], max_length=50)),
                ('html_template', models.TextField()),
                ('css_styles', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, upload_to='certificate_templates/')),
                ('logo_image', models.ImageField(blank=True, upload_to='certificate_templates/')),
                ('layout_settings', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('FIRST_LESSON', 'First Lesson Complete'), ('PERFECT_UNIT', 'Perfect Unit Score'), ('SPEED_LEARNER', 'Speed Learner'), ('CONSISTENT_LEARNER', '7-Day Streak'), ('HELPER', 'Helped Others'), ('ALL_SKILLS', 'All Skills Mastered')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('points_awarded', models.IntegerField(default=0)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('related_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson')),
                ('related_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.unit')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('LEVEL_COMPLETE', 'Level Completion'), ('SKILL_MASTERY', 'Skill Mastery'), ('PERFECT_SCORE', 'Perfect Score Achievement'), ('PARTICIPATION', 'Participation Award')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('template_name', models.CharField(max_length=100)),
                ('shields_earned', models.IntegerField(default=0)),
                ('listening_shields', models.IntegerField(default=0)),
                ('reading_shields', models.IntegerField(default=0)),
                ('writing_shields', models.IntegerField(default=0)),
                ('speaking_shields', models.IntegerField(default=0)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('certificate_pdf', models.FileField(blank=True, upload_to='certificates/')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.ylelevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
