# Generated by Django 6.1.1 on 2026-09-17 07:20

import django.db.models.deletion
from django.db import migrations, models


def level_types_to_level_field(apps, schema_editor):
    """STARTERS/MOVERS/FLYERS template types become LEVEL with the matching level set."""
    CertificateTemplate = apps.get_model("certification", "CertificateTemplate")
    YLELevel = apps.get_model("courses", "YLELevel")
    for template in CertificateTemplate.objects.filter(template_type__in=["STARTERS", "MOVERS", "FLYERS"]):
        template.level = YLELevel.objects.filter(short_code__iexact=template.template_type).first()
        template.template_type = "LEVEL"
        template.save(update_fields=["level", "template_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
        ('courses', '0005_cambridge_levels_to_b2'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_templates', to='courses.ylelevel'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='template_type',
            field=models.CharField(choices=[('LEVEL', 'Level Completion'), ('SKILL', 'Skill Mastery'), ('ACHIEVEMENT', 'Special Achievement')], max_length=50),
        ),
        migrations.RunPython(level_types_to_level_field, migrations.RunPython.noop),
    ]
