# Generated by Django 6.1.1 on 2026-09-20 02:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_certificate_template_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
    ]
