# Generated by Django 6.0.2 on 2026-02-12 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, upload_to='teacher_profiles/')),
                ('bio', models.TextField(blank=True, help_text='Short biography or introduction')),
                ('qualifications', models.TextField(blank=True, help_text='Educational qualifications and certifications (e.g., CELTA, TESOL)')),
                ('years_of_experience', models.IntegerField(default=0)),
                ('teaches_starters', models.BooleanField(default=False)),
                ('teaches_movers', models.BooleanField(default=False)),
                ('teaches_flyers', models.BooleanField(default=False)),
                ('specializes_listening', models.BooleanField(default=False)),
                ('specializes_reading', models.BooleanField(default=False)),
                ('specializes_writing', models.BooleanField(default=False)),
                ('specializes_speaking', models.BooleanField(default=False)),
                ('date_joined', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=20)),
                ('availability_schedule', models.JSONField(blank=True, default=dict, help_text='Weekly availability schedule')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average student rating out of 5.00', max_digits=3)),
                ('total_classes_taught', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CV', 'Curriculum Vitae / Resume'), ('DEGREE', 'Degree Certificate'), ('DIPLOMA', 'Diploma / Certificate'), ('TEACHING_CERT', 'Teaching Certification (CELTA, TESOL, etc.)'), ('ID_PROOF', 'ID Proof / Passport'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('POLICE_CLEARANCE', 'Police Clearance'), ('OTHER', 'Other Document')], max_length=50)),
                ('title', models.CharField(help_text="E.g., 'Bachelor of Arts in English', 'CELTA Certificate'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details about the document')),
                ('document', models.FileField(help_text='Upload PDF, DOC, DOCX, or image files', upload_to='teacher_documents/')),
                ('issuing_authority', models.CharField(blank=True, help_text="E.g., 'Cambridge Assessment', 'University of Colombo'", max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='If applicable (e.g., police clearance)', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Mark as verified after review')),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teachers.teacher')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_teacher_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherHourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in LKR or currency', max_digits=10)),
                ('currency', models.CharField(choices=[('LKR', 'Sri Lankan Rupee'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], default='LKR', max_length=3)),
                ('effective_from', models.DateField(help_text='Date from which this rate is applicable')),
                ('effective_until', models.DateField(blank=True, help_text='Leave blank if current rate', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Only one rate should be marked as current')),
                ('reason', models.TextField(blank=True, help_text="Reason for rate change (e.g., 'Annual increment', 'Performance bonus', 'Promotion')")),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teacher_rates', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rates', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-effective_from'],
                'unique_together': {('teacher', 'effective_from')},
            },
        ),
    ]
