# Generated by Django 6.0.2 on 2026-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_skill_specializations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tier name (e.g., 'Senior Teacher', 'Junior Teacher')", max_length=100)),
                ('payment_type', models.CharField(choices=[('HOURLY', 'Hourly Rate'), ('FIXED', 'Fixed Amount')], help_text='Type of payment: hourly rate or fixed amount', max_length=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate (used when payment_type is HOURLY)', max_digits=10, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount (used when payment_type is FIXED)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Tier',
                'verbose_name_plural': 'Payment Tiers',
                'ordering': ['name'],
            },
        ),
    ]
