# Generated by Django 6.0.2 on 2026-02-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_add_payment_tier_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTier',
        ),
    ]
