# Generated by Django 6.0.2 on 2026-02-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_delete_paymenttier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherHourlyRate',
        ),
    ]
