# Generated by Django 6.0.2 on 2026-02-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('skill_listening', models.BooleanField(default=False)),
                ('skill_reading', models.BooleanField(default=False)),
                ('skill_writing', models.BooleanField(default=False)),
                ('skill_speaking', models.BooleanField(default=False)),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video Lesson'), ('INTERACTIVE', 'Interactive Activity'), ('READ', 'Reading Material'), ('AUDIO', 'Audio Lesson'), ('GAME', 'Educational Game')], max_length=50)),
                ('content_url', models.URLField(blank=True)),
                ('content_file', models.FileField(blank=True, upload_to='lesson_content/')),
                ('content_html', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(default=15)),
                ('completion_points', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['unit', 'order'],
            },
        ),
        migrations.CreateModel(
            name='YLELevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_code', models.CharField(max_length=20, unique=True)),
                ('cefr_level', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('age_range_min', models.IntegerField()),
                ('age_range_max', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(max_length=100)),
                ('color_theme', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('COLORING', 'Coloring Activity'), ('MATCHING', 'Matching Pairs'), ('DIFFERENCES', 'Find Differences'), ('DRAG_DROP', 'Drag and Drop'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('FILL_BLANK', 'Fill in the Blanks'), ('WORD_PUZZLE', 'Word Puzzle'), ('LISTENING_COMPREHENSION', 'Listening Comprehension')], max_length=50)),
                ('activity_data', models.JSONField()),
                ('max_points', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.lesson')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, upload_to='unit_thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires_completion_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='courses.unit')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.ylelevel')),
            ],
            options={
                'ordering': ['level', 'order'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.unit'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_code', models.CharField(max_length=20, unique=True)),
                ('schedule', models.JSONField(default=list, help_text='Class schedule: day, time, duration')),
                ('max_students', models.IntegerField(default=25)),
                ('current_enrollment', models.IntegerField(default=0)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to='teachers.teacher')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.ylelevel')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['level', 'class_name'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assessment_type', models.CharField(choices=[('UNIT_TEST', 'Unit Test'), ('LEVEL_TEST', 'Level Final Exam'), ('PRACTICE_TEST', 'Practice Test')], max_length=50)),
                ('time_limit_minutes', models.IntegerField(default=30)),
                ('tests_listening', models.BooleanField(default=True)),
                ('tests_reading', models.BooleanField(default=True)),
                ('tests_writing', models.BooleanField(default=True)),
                ('tests_speaking', models.BooleanField(default=False)),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('questions_data', models.JSONField()),
                ('max_score', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.unit')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.ylelevel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('unit', 'order')},
        ),
    ]
