# Generated by Django 6.0.2 on 2026-03-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ylelevel',
            name='cefr_level',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
