# Generated by Django 6.1.1 on 2026-09-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_make_cefr_level_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
