# Generated by Django 6.1.1 on 2026-09-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_pre_junior_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0, help_text='Order within the level'),
        ),
    ]
